// This file is auto-generated by pydantic-converter
// Do not modify this file manually
/**
 * This is dummy value to make the root schema valid.
 */
export type __All = AnotherSample | Sample | ModelImportedFromSomewhere | Option;
export type Name = string;
export type Age = number;
export type IsActive = boolean;
export type Name1 = string;
export type Age1 = number;
export type Option = "A" | "B";
export type Args = string;
export type Imported = ModelImportedFromSomewhere[];

export interface AnotherSample {
  name: Name;
  age: Age;
  isActive: IsActive;
  sample: Sample | null;
}
export interface Sample {
  name: Name1;
  age: Age1;
  option: Option;
  imported: Imported;
}
export interface ModelImportedFromSomewhere {
  args: Args;
}
